- hosts: localhost
  connection: local
  remote_user: root
  gather_facts: yes
  become: true
  vars:
    dir: /home/ec2-user/testdir

  tasks:
  - name: Creates directory
    file:
      path: "{{ dir }}"
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0755
      recurse: yes

